language: node_js
node_js: "12"
services:
  - mysql
branches:
  only:
  - master
cache:
  directories:
    - node_modules
before_install:
  # - echo ";\n\n" | mysql -u root
  - mysql -e 'ALTER USER 'root'@'localhost' IDENTIFIED BY 'root';'
  - mysql -e 'CREATE DATABASE testdb;'
