language: node_js
node_js: "12"
services:
  - mysql
branches:
  only:
  - master
cache:
  directories:
    - node_modules
before_install:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mysql -e 'CREATE DATABASE testdb;'
