language: node_js
node_js: "12"
services:
  - mysql
branches:
  only:
  - master
cache:
  directories:
    - node_modules
before_install:
  # - echo ";\n\n" | mysql -u root
  - mysql -e 'USE mysql;UPDATE user SET password=PASSWORD('root') WHERE user='root';FLUSH PRIVILEGES;'
  - mysql -e 'CREATE DATABASE testdb;'
