language: node_js
node_js: "12"
services:
  - mysql
branches:
  only:
  - master
cache:
  directories:
    - node_modules
before_install:
  - mysql -e 'CREATE USER test WITH PASSWORD 'test';'
  - mysql -e 'ALTER USER test CREATEDB;'
  - mysql -e 'CREATE DATABASE testdb;'
